# get drug codelists

# 67 drugs in total

card_drugs <- getDrugIngredientCodes(
  cdm = cdm,
  name = c("abciximab",
    "acenocoumarol",
    "aloxiprin",
    "alteplase", 
    "ancrod",
    "anistreplase", 
    "antithrombin III", 
    "APADAMTASE ALFA", 
    "apixaban", 
    "argatroban", 
    "Aspergillus flavus var. oryzae protease", 
    "aspirin",
    "bemiparin", 
    "beraprost sodium", 
    "betrixaban", 
    "bivalirudin", 
    "cangrelor", 
    "caplacizumab", 
    "Carbasalate Calcium", 
    "cilostazol", 
    "clopidogrel", 
    "Clorindione", 
    "dabigatran etexilate", 
    "dalteparin", 
    "danaparoid", 
    "defibrotide", 
    "desirudin",
    "dicumarol", 
    "dipyridamole", 
    "drotrecogin alfa", 
    "edoxaban",
    "enoxaparin", 
    "epoprostenol", 
    "eptifibatide", 
    "fluindione", 
    "fondaparinux", 
    "heparin", 
    "iloprost", 
    "indobufen", 
    "lepirudin", 
    "limaprost", 
    "Melagatran", 
    "nadroparin", 
    "parnaparin", 
    "phenindione", 
    "phenprocoumon", 
    "plasmin", 
    "prasugrel", 
    "protein C", 
    "reteplase", 
    "reviparin", 
    "rivaroxaban", 
    "selexipag", 
    "streptokinase", 
    "sulodexide", 
    "tenecteplase", 
    "ticagrelor", 
    "ticlopidine", 
    "tinzaparin", 
    "tioclomarol", 
    "tirofiban", 
    "treprostinil", 
    "triflusal", 
    "urokinase", 
    "vorapaxar", 
    "warfarin", 
    "Ximelagatran" 
  ),
  nameStyle = "{concept_name}_{concept_id}",
  type = "codelist"
)

exportCodelist(card_drugs, path = here("Cohorts", "drugs"), type = "csv")
