# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    cohort_code_use = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_log_file = FALSE,
    crm_probabilities = FALSE,
    crm_coefficients = FALSE,
    crm_probabilities_by_country = FALSE,
    crm_coefficients_by_country = FALSE,
    mms_probabilities = FALSE,
    cox_coefficients = FALSE,
    mms_probabilities_by_country = FALSE,
    cox_coefficients_by_country = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_cohort_name,
      input$cohort_code_use_codelist_name,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name %in% input$cohort_code_use_cohort_name,
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_count <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_count_cdm_name,
      input$summarise_cohort_count_cohort_name,
      input$summarise_cohort_count_variable_name,
      input$summarise_cohort_count_condition,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })

  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) 
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
    
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_country,
      input$summarise_characteristics_age_group,
      input$summarise_characteristics_sex,
      input$summarise_characteristics_ses,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$country %in% input$summarise_characteristics_country,
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$sex %in% input$summarise_characteristics_sex,
        .data$ses %in% input$summarise_characteristics_ses
      ) |>
      dplyr::mutate(variable_level = sub(" mi$", "", variable_level),
                    variable_level = sub(" stroke$", "", variable_level),
                    variable_level = dplyr::case_when(
                      variable_level == "Acute" ~ "MI",
                      variable_level == "Stroke broad" ~ "Stroke",
                      TRUE ~ variable_level
                    ))
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    }
  )

  # crm_probabilities -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$crm_probabilities <- TRUE
  }) |>
    shiny::bindEvent(
      input$crm_probabilities_cdm_name,
      input$crm_probabilities_cohort_name,
      input$crm_probabilities_time,
      input$crm_probabilities_state,
      input$crm_probabilities_variable_name,
      input$crm_probabilities_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$crm_probabilities, {
    if (updateButtons$crm_probabilities == TRUE) {
      output$update_message_crm_probabilities <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_crm_probabilities <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_crm_probabilities, {
    updateButtons$crm_probabilities <- FALSE
  })

  ## get crm_probabilities data
  getCrmProbabilitiesData <- shiny::eventReactive(input$update_crm_probabilities, {
    data[["crm_probabilities"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$crm_probabilities_cdm_name,
        .data$variable_name %in% input$crm_probabilities_variable_name,
        .data$estimate_name %in% input$crm_probabilities_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$crm_probabilities_cohort_name) |>
      omopgenerics::filterAdditional(
        .data$time %in% input$crm_probabilities_time,
        .data$state %in% input$crm_probabilities_state
      ) |>
      omopgenerics::splitAdditional() |>
      dplyr::mutate(time = as.numeric(time),
                    estimate_value = as.numeric(estimate_value)) |>
      omopgenerics::uniteAdditional(cols = c("time", "state"))
  })
  getCrmProbabilitiesTidy <- shiny::reactive({
    tidyDT(getCrmProbabilitiesData(), input$crm_probabilities_tidy_columns, input$crm_probabilities_tidy_pivot_estimates)
  })
  output$crm_probabilities_tidy <- DT::renderDT({
    getCrmProbabilitiesTidy()
  })
  output$crm_probabilities_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCrmProbabilitiesData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCrmProbabilitiesTable <- shiny::reactive({
    getCrmProbabilitiesData() |>
      simpleTable(
        header = input$crm_probabilities_table_header,
        group = input$crm_probabilities_table_group_column,
        hide = input$crm_probabilities_table_hide
      )
  })
  output$crm_probabilities_table <- gt::render_gt({
    getCrmProbabilitiesTable()
  })
  output$crm_probabilities_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$crm_probabilities_table_format),
    content = function(file) {
      gt::gtsave(getCrmProbabilitiesTable(), file)
    }
  )
  
  getSummariseCrmProbabilitiesPlot <- shiny::reactive({
    getCrmProbabilitiesData() |>
    omopgenerics::splitAdditional() |>
    dplyr::mutate(estimate_value = as.numeric(estimate_value),
                    time = as.numeric(time)) |>
      ggplot(aes(x = time, y = estimate_value, color = state, group = state)) +
      geom_line(linewidth = 0.8) +
      coord_cartesian(xlim = c(0, 28)) +
      facet_wrap(~cdm_name + group_level) +
      labs(x = "Time",
           y = "Probability",
           color = "State") +
      theme_minimal()
  })
  
  output$summarise_crm_probabilities_plot <- shiny::renderUI({
    x <- getSummariseCrmProbabilitiesPlot()
    renderInteractivePlot(x, input$summarise_crm_probabilities_plot_interactive)
  })
  output$summarise_crm_probabilities_plot_download <- shiny::downloadHandler(
    filename = "plot_crm_probabilities.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCrmProbabilitiesPlot(),
        width = as.numeric(input$summarise_crm_probabilities_plot_width),
        height = as.numeric(input$summarise_crm_probabilities_plot_height),
        units = input$summarise_crm_probabilities_plot_units,
        dpi = as.numeric(input$summarise_crm_probabilities_plot_dpi)
      )
    }
  )

  # crm_coefficients -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$crm_coefficients <- TRUE
  }) |>
    shiny::bindEvent(
      input$crm_coefficients_cdm_name,
      input$crm_coefficients_cohort_name,
      input$crm_coefficients_variable_name,
      input$crm_coefficients_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$crm_coefficients, {
    if (updateButtons$crm_coefficients == TRUE) {
      output$update_message_crm_coefficients <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_crm_coefficients <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_crm_coefficients, {
    updateButtons$crm_coefficients <- FALSE
  })

  ## get crm_coefficients data
  getCrmCoefficientsData <- shiny::eventReactive(input$update_crm_coefficients, {
    data[["crm_coefficients"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$crm_coefficients_cdm_name,
        .data$variable_name %in% input$crm_coefficients_variable_name,
        .data$estimate_name %in% input$crm_coefficients_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$crm_coefficients_cohort_name)
  })
  getCrmCoefficientsTidy <- shiny::reactive({
    tidyDT(getCrmCoefficientsData(), input$crm_coefficients_tidy_columns, input$crm_coefficients_tidy_pivot_estimates)
  })
  output$crm_coefficients_tidy <- DT::renderDT({
    getCrmCoefficientsTidy()
  })
  output$crm_coefficients_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCrmCoefficientsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCrmCoefficientsTable <- shiny::reactive({
    getCrmCoefficientsData() |>
      simpleTable(
        header = input$crm_coefficients_table_header,
        group = input$crm_coefficients_table_group_column,
        hide = input$crm_coefficients_table_hide
      )
  })
  output$crm_coefficients_table <- gt::render_gt({
    getCrmCoefficientsTable()
  })
  output$crm_coefficients_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$crm_coefficients_table_format),
    content = function(file) {
      gt::gtsave(getCrmCoefficientsTable(), file)
    }
  )
  
  getSummariseCrmCoefficientsPlot <- shiny::reactive({
    getCrmCoefficientsData() |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value)) |>
      tidyr::pivot_wider(
        names_from = estimate_name,
        values_from = estimate_value
      ) |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se = as.numeric(se),
        coef_exp = round(exp(coef), digits = 2),
        lci = round(exp(coef - qnorm(0.975)*se), digits = 2),
        uci = round(exp(coef + qnorm(0.975)*se), digits = 2),
        sig = ifelse(coef_exp > 1 & lci > 1 | coef_exp < 1 & uci < 1, "sig", "not sig")
      ) |>
      dplyr::filter(uci != "Inf") |>
      ggplot(aes(x = coef_exp, y = variable_level, colour = sig, fill = sig)) +
      geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
      geom_point(size = 3, position = ggstance::position_dodgev(height = 0.6)) +
      geom_errorbarh(aes(xmin = lci, xmax = uci), height = 0.2,
                     position = ggstance::position_dodgev(height = 0.6)) +
      facet_wrap( ~ group_level) +
      labs(
        x = "Hazard ratio (log scale) with 95% CI",
        y = NULL,
        colour = "Variable"
      ) +
      theme_minimal()
  })
  
  output$summarise_crm_coefficients_plot <- shiny::renderUI({
    x <- getSummariseCrmCoefficientsPlot()
    renderInteractivePlot(x, input$summarise_crm_coefficients_plot_interactive)
  })
  output$summarise_crm_coefficients_plot_download <- shiny::downloadHandler(
    filename = "plot_crm_coefficients.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCrmCoefficientsPlot(),
        width = as.numeric(input$summarise_crm_coefficients_plot_width),
        height = as.numeric(input$summarise_crm_coefficients_plot_height),
        units = input$summarise_crm_coefficients_plot_units,
        dpi = as.numeric(input$summarise_crm_coefficients_plot_dpi)
      )
    }
  )

  # crm_probabilities_by_country -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$crm_probabilities_by_country <- TRUE
  }) |>
    shiny::bindEvent(
      input$crm_probabilities_by_country_cdm_name,
      input$crm_probabilities_by_country_cohort_name,
      input$crm_probabilities_by_country_time,
      input$crm_probabilities_by_country_state,
      input$crm_probabilities_by_country_variable_name,
      input$crm_probabilities_by_country_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$crm_probabilities_by_country, {
    if (updateButtons$crm_probabilities_by_country == TRUE) {
      output$update_message_crm_probabilities_by_country <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_crm_probabilities_by_country <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_crm_probabilities_by_country, {
    updateButtons$crm_probabilities_by_country <- FALSE
  })

  ## get crm_probabilities_by_country data
  getCrmProbabilitiesByCountryData <- shiny::eventReactive(input$update_crm_probabilities_by_country, {
    data[["crm_probabilities_by_country"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$crm_probabilities_by_country_cdm_name,
        .data$variable_name %in% input$crm_probabilities_by_country_variable_name,
        .data$estimate_name %in% input$crm_probabilities_by_country_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$crm_probabilities_by_country_cohort_name) |>
      omopgenerics::splitAdditional() |>
      dplyr::mutate(time = as.numeric(.data$time),
                    estimate_value = as.numeric(.data$estimate_value)) |>
      dplyr::filter(
        .data$time %in% input$crm_probabilities_by_country_time,
        .data$state %in% input$crm_probabilities_by_country_state
      )
  })
  getCrmProbabilitiesByCountryTidy <- shiny::reactive({
    tidyDT(getCrmProbabilitiesByCountryData(), input$crm_probabilities_by_country_tidy_columns, input$crm_probabilities_by_country_tidy_pivot_estimates)
  })
  output$crm_probabilities_by_country_tidy <- DT::renderDT({
    getCrmProbabilitiesByCountryTidy()
  })
  output$crm_probabilities_by_country_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCrmProbabilitiesByCountryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCrmProbabilitiesByCountryTable <- shiny::reactive({
    getCrmProbabilitiesByCountryData() |>
      simpleTable(
        header = input$crm_probabilities_by_country_table_header,
        group = input$crm_probabilities_by_country_table_group_column,
        hide = input$crm_probabilities_by_country_table_hide
      )
  })
  output$crm_probabilities_by_country_table <- gt::render_gt({
    getCrmProbabilitiesByCountryTable()
  })
  output$crm_probabilities_by_country_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$crm_probabilities_by_country_table_format),
    content = function(file) {
      gt::gtsave(getCrmProbabilitiesByCountryTable(), file)
    }
  )
  
  getSummariseCrmProbabilitiesByCountryPlot <- shiny::reactive({
    getCrmProbabilitiesByCountryData()|>
      ggplot(aes(x = time, y = estimate_value, color = state, group = state)) +
      geom_line(linewidth = 0.8) +
      coord_cartesian(xlim = c(0, 28)) +
      facet_wrap(~cdm_name + group_level) +
      labs(x = "Time",
           y = "Probability",
           color = "State") +
      theme_minimal()
  })
  
  output$summarise_crm_probabilities_by_country_plot <- shiny::renderUI({
    x <- getSummariseCrmProbabilitiesByCountryPlot()
    renderInteractivePlot(x, input$summarise_crm_probabilities_by_country_plot_interactive)
  })
  output$summarise_crm_probabilities_by_country_plot_download <- shiny::downloadHandler(
    filename = "plot_crm_probabilities_by_country.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCrmProbabilitiesByCountryPlot(),
        width = as.numeric(input$summarise_crm_probabilities_by_country_plot_width),
        height = as.numeric(input$summarise_crm_probabilities_by_country_plot_height),
        units = input$summarise_crm_probabilities_by_country_plot_units,
        dpi = as.numeric(input$summarise_crm_probabilities_by_country_plot_dpi)
      )
    }
  )

  # crm_coefficients_by_country -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$crm_coefficients_by_country <- TRUE
  }) |>
    shiny::bindEvent(
      input$crm_coefficients_by_country_cdm_name,
      input$crm_coefficients_by_country_cohort_name,
      input$crm_coefficients_by_country_variable_name,
      input$crm_coefficients_by_country_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$crm_coefficients_by_country, {
    if (updateButtons$crm_coefficients_by_country == TRUE) {
      output$update_message_crm_coefficients_by_country <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_crm_coefficients_by_country <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_crm_coefficients_by_country, {
    updateButtons$crm_coefficients_by_country <- FALSE
  })

  ## get crm_coefficients_by_country data
  getCrmCoefficientsByCountryData <- shiny::eventReactive(input$update_crm_coefficients_by_country, {
    data[["crm_coefficients_by_country"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$crm_coefficients_by_country_cdm_name,
        .data$variable_name %in% input$crm_coefficients_by_country_variable_name,
        .data$estimate_name %in% input$crm_coefficients_by_country_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$crm_coefficients_by_country_cohort_name)
  })
  getCrmCoefficientsByCountryTidy <- shiny::reactive({
    tidyDT(getCrmCoefficientsByCountryData(), input$crm_coefficients_by_country_tidy_columns, input$crm_coefficients_by_country_tidy_pivot_estimates)
  })
  output$crm_coefficients_by_country_tidy <- DT::renderDT({
    getCrmCoefficientsByCountryTidy()
  })
  output$crm_coefficients_by_country_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCrmCoefficientsByCountryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCrmCoefficientsByCountryTable <- shiny::reactive({
    getCrmCoefficientsByCountryData() |>
      simpleTable(
        header = input$crm_coefficients_by_country_table_header,
        group = input$crm_coefficients_by_country_table_group_column,
        hide = input$crm_coefficients_by_country_table_hide
      )
  })
  output$crm_coefficients_by_country_table <- gt::render_gt({
    getCrmCoefficientsByCountryTable()
  })
  output$crm_coefficients_by_country_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$crm_coefficients_by_country_table_format),
    content = function(file) {
      gt::gtsave(getCrmCoefficientsByCountryTable(), file)
    }
  )
  
  getSummariseCrmCoefficientsByCountryPlot <- shiny::reactive({
    getCrmCoefficientsByCountryData() |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value)) |>
      tidyr::pivot_wider(
        names_from = estimate_name,
        values_from = estimate_value
      ) |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se = as.numeric(se),
        coef_exp = round(exp(coef), digits = 2),
        lci = round(exp(coef - qnorm(0.975)*se), digits = 2),
        uci = round(exp(coef + qnorm(0.975)*se), digits = 2),
        sig = ifelse(coef_exp > 1 & lci > 1 | coef_exp < 1 & uci < 1, "sig", "not sig")
      ) |>
      dplyr::filter(uci != "Inf") |>
      ggplot(aes(x = coef_exp, y = variable_level, colour = sig, fill = sig)) +
      geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
      geom_point(size = 3, position = ggstance::position_dodgev(height = 0.6)) +
      geom_errorbarh(aes(xmin = lci, xmax = uci), height = 0.2,
                     position = ggstance::position_dodgev(height = 0.6)) +
      facet_wrap( ~ group_level) +
      labs(
        x = "Hazard ratio (log scale) with 95% CI",
        y = NULL,
        colour = "Variable"
      ) +
      theme_minimal()
  })
  
  output$summarise_crm_coefficients_by_country_plot <- shiny::renderUI({
    x <- getSummariseCrmCoefficientsByCountryPlot()
    renderInteractivePlot(x, input$summarise_crm_coefficients_by_country_plot_interactive)
  })
  output$summarise_crm_coefficients_by_countryplot_download <- shiny::downloadHandler(
    filename = "plot_crm_coefficients_by_country.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCrmCoefficientsPlot(),
        width = as.numeric(input$summarise_crm_coefficients_by_country_plot_width),
        height = as.numeric(input$summarise_crm_coefficients_by_country_plot_height),
        units = input$summarise_crm_coefficients_by_country_plot_units,
        dpi = as.numeric(input$summarise_crm_coefficients_by_country_plot_dpi)
      )
    }
  )

  # mms_probabilities -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$mms_probabilities <- TRUE
  }) |>
    shiny::bindEvent(
      input$mms_probabilities_cdm_name,
      input$mms_probabilities_cohort_name,
      input$mms_probabilities_state,
      input$mms_probabilities_variable_name,
      input$mms_probabilities_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$mms_probabilities, {
    if (updateButtons$mms_probabilities == TRUE) {
      output$update_message_mms_probabilities <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_mms_probabilities <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_mms_probabilities, {
    updateButtons$mms_probabilities <- FALSE
  })

  ## get mms_probabilities data
  getMmsProbabilitiesData <- shiny::eventReactive(input$update_mms_probabilities, {
    data[["mms_probabilities"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$mms_probabilities_cdm_name,
        .data$variable_name %in% input$mms_probabilities_variable_name,
        .data$estimate_name %in% input$mms_probabilities_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$mms_probabilities_cohort_name) |>
      omopgenerics::splitAdditional() |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value),
                    time = as.numeric(time)) |>
      dplyr::filter(.data$state %in% input$mms_probabilities_state)
  })
  getMmsProbabilitiesTidy <- shiny::reactive({
    tidyDT(getMmsProbabilitiesData(), input$mms_probabilities_tidy_columns, input$mms_probabilities_tidy_pivot_estimates)
  })
  output$mms_probabilities_tidy <- DT::renderDT({
    getMmsProbabilitiesTidy()
  })
  output$mms_probabilities_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getMmsProbabilitiesData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getMmsProbabilitiesTable <- shiny::reactive({
    getMmsProbabilitiesData() |>
      simpleTable(
        header = input$mms_probabilities_table_header,
        group = input$mms_probabilities_table_group_column,
        hide = input$mms_probabilities_table_hide
      )
  })
  output$mms_probabilities_table <- gt::render_gt({
    getMmsProbabilitiesTable()
  })
  output$mms_probabilities_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$mms_probabilities_table_format),
    content = function(file) {
      gt::gtsave(getMmsProbabilitiesTable(), file)
    }
  )
  
  getSummariseMmsProbabilitiesPlot <- shiny::reactive({
    getMmsProbabilitiesData() |>
      dplyr::mutate(step = 1) |>
      dplyr::bind_rows(
        getMmsProbabilitiesData() |>
          dplyr::group_by(state) |>
          dplyr::mutate(time = dplyr::lead(time), step = -1) |>
          dplyr::ungroup()
      ) |>
      # drop rows where lead() produced NA time
      dplyr::filter(!is.na(time)) |>
      dplyr::arrange(time, state, step) |>
      ggplot(aes(x = time, y = estimate_value, fill = state, group = state)) +
      geom_area(color = "black") +
      facet_wrap(~ group_level) +
      coord_cartesian(xlim = c(0, 5*365)) +
      scale_fill_manual(values = c(
        "#4C6A92", "#7A9E7E", "#8C6A8C"
      )) +
      labs(x = "Time",
           y = "Probability",
           fill = "State") +
      theme_minimal()
  })
  
  output$summarise_mms_probabilities_plot <- shiny::renderUI({
    x <- getSummariseMmsProbabilitiesPlot()
    renderInteractivePlot(x, input$summarise_mms_probabilities_plot_interactive)
  })
  output$summarise_mms_probabilities_plot_download <- shiny::downloadHandler(
    filename = "plot_msm_probabilities.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseMmsProbabilitiesPlot(),
        width = as.numeric(input$summarise_mms_probabilities_plot_width),
        height = as.numeric(input$summarise_mms_probabilities_plot_height),
        units = input$summarise_mms_probabilities_plot_units,
        dpi = as.numeric(input$summarise_mms_probabilities_plot_dpi)
      )
    }
  )

  # cox_coefficients -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cox_coefficients <- TRUE
  }) |>
    shiny::bindEvent(
      input$cox_coefficients_cdm_name,
      input$cox_coefficients_cohort_name,
      input$cox_coefficients_variable_name,
      input$cox_coefficients_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cox_coefficients, {
    if (updateButtons$cox_coefficients == TRUE) {
      output$update_message_cox_coefficients <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cox_coefficients <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cox_coefficients, {
    updateButtons$cox_coefficients <- FALSE
  })

  ## get cox_coefficients data
  getCoxCoefficientsData <- shiny::eventReactive(input$update_cox_coefficients, {
    data[["cox_coefficients"]] |>
    dplyr::filter(
    .data$cdm_name %in% input$cox_coefficients_cdm_name,
    .data$variable_name %in% input$cox_coefficients_variable_name,
    .data$estimate_name %in% input$cox_coefficients_estimate_name
    ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$cox_coefficients_cohort_name) |>
      tidyr::pivot_wider(
        names_from = estimate_name,
        values_from = estimate_value
      ) |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se = as.numeric(se),
        coef_exp = round(exp(coef), digits = 2),
        lci = round(exp(coef - qnorm(0.975)*se), digits = 2),
        uci = round(exp(coef + qnorm(0.975)*se), digits = 2)
      ) |>
      dplyr::filter(uci != "Inf") |>
      dplyr::select(-c(coef, se, se_robust)) |>
      tidyr::pivot_longer(
        cols = c(coef_exp, lci, uci),
        names_to = "estimate_name",
        values_to = "estimate_value"
      ) |>
      dplyr::mutate(
        trans = stringr::str_extract(variable_level, "(?<=trans=)\\d+") |> as.numeric(),
        variable = stringr::str_extract(variable_level, "(?<=:)\\w+") |>
          stringr::str_remove("^sex")
      ) |>
      dplyr::mutate(trans = dplyr::case_when(
        trans == "1" ~ "Treatment -> No treatment",
        trans == "2" ~ "No treatment -> Treatment",
        trans == "3" ~ "Treatment -> Death",
        trans == "4" ~ "No treatment -> Death"
      )) |>
      dplyr::mutate(variable_level = paste0(trans, ": ", variable)) |>
      dplyr::select(-c(trans, variable)) |>
      dplyr::select(c(result_id, cdm_name, group_name, group_level, strata_name, strata_level, variable_name,
                      variable_level, estimate_name, estimate_type, estimate_value, additional_name, additional_level)) |>
      omopgenerics::newSummarisedResult()
  })
  getCoxCoefficientsTidy <- shiny::reactive({
    tidyDT(getCoxCoefficientsData(), input$cox_coefficients_tidy_columns, input$cox_coefficients_tidy_pivot_estimates)
  })
  output$cox_coefficients_tidy <- DT::renderDT({
    getCoxCoefficientsTidy()
  })
  output$cox_coefficients_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCoxCoefficientsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCoxCoefficientsTable <- shiny::reactive({
    getCoxCoefficientsData() |>
      simpleTable(
        header = input$cox_coefficients_table_header,
        group = input$cox_coefficients_table_group_column,
        hide = input$cox_coefficients_table_hide
      )
  })
  output$cox_coefficients_table <- gt::render_gt({
    getCoxCoefficientsTable()
  })
  output$cox_coefficients_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$cox_coefficients_table_format),
    content = function(file) {
      gt::gtsave(getCoxCoefficientsTable(), file)
    }
  )
  
  getCoxCoefficientsPlot <- shiny::reactive({
    getCoxCoefficientsData() |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value)) |>
      tidyr::pivot_wider(
        names_from = estimate_name,
        values_from = estimate_value
      ) |>
      ggplot(aes(x = coef_exp, y = variable_level, colour = variable_level)) +
      geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
      geom_point(size = 3, position = ggstance::position_dodgev(height = 0.6)) +
      geom_errorbarh(aes(xmin = lci, xmax = uci), height = 0.2,
                     position = ggstance::position_dodgev(height = 0.6)) +
      facet_wrap( ~ group_level) +
      labs(
        x = "Hazard ratio (log scale) with 95% CI",
        y = NULL,
        colour = "Variable"
      ) +
      theme_minimal(base_size = 14) +
      theme(
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(hjust = 0)
      ) 
  })
  
  output$summarise_cox_coefficients_plot <- shiny::renderUI({
    x <- getCoxCoefficientsPlot()
    renderInteractivePlot(x, input$summarise_cox_coefficients_plot_interactive)
  })
  output$summarise_cox_coefficients_plot_download <- shiny::downloadHandler(
    filename = "plot_cox_coefficients.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot =  getCoxCoefficientsPlot(),
        width = as.numeric(input$summarise_cox_coefficients_plot_width),
        height = as.numeric(input$summarise_cox_coefficients_plot_height),
        units = input$summarise_cox_coefficients_plot_units,
        dpi = as.numeric(input$summarise_cox_coefficients_plot_dpi)
      )
    }
  )

  # mms_probabilities_by_country -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$mms_probabilities_by_country <- TRUE
  }) |>
    shiny::bindEvent(
      input$mms_probabilities_by_country_cdm_name,
      input$mms_probabilities_by_country_cohort_name,
      input$mms_probabilities_by_country_state,
      input$mms_probabilities_by_country_variable_name,
      input$mms_probabilities_by_country_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$mms_probabilities_by_country, {
    if (updateButtons$mms_probabilities_by_country == TRUE) {
      output$update_message_mms_probabilities_by_country <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_mms_probabilities_by_country <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_mms_probabilities_by_country, {
    updateButtons$mms_probabilities_by_country <- FALSE
  })

  ## get mms_probabilities_by_country data
  getMmsProbabilitiesByCountryData <- shiny::eventReactive(input$update_mms_probabilities_by_country, {
    data[["mms_probabilities_by_country"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$mms_probabilities_by_country_cdm_name,
        .data$variable_name %in% input$mms_probabilities_by_country_variable_name,
        .data$estimate_name %in% input$mms_probabilities_by_country_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$mms_probabilities_by_country_cohort_name) |>
      omopgenerics::filterAdditional(.data$state %in% input$mms_probabilities_by_country_state)
  })
  getMmsProbabilitiesByCountryTidy <- shiny::reactive({
    tidyDT(getMmsProbabilitiesByCountryData(), input$mms_probabilities_by_country_tidy_columns, input$mms_probabilities_by_country_tidy_pivot_estimates)
  })
  output$mms_probabilities_by_country_tidy <- DT::renderDT({
    getMmsProbabilitiesByCountryTidy()
  })
  output$mms_probabilities_by_country_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getMmsProbabilitiesByCountryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getMmsProbabilitiesByCountryTable <- shiny::reactive({
    getMmsProbabilitiesByCountryData() |>
      simpleTable(
        header = input$mms_probabilities_by_country_table_header,
        group = input$mms_probabilities_by_country_table_group_column,
        hide = input$mms_probabilities_by_country_table_hide
      )
  })
  output$mms_probabilities_by_country_table <- gt::render_gt({
    getMmsProbabilitiesByCountryTable()
  })
  output$mms_probabilities_by_country_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$mms_probabilities_by_country_table_format),
    content = function(file) {
      gt::gtsave(getMmsProbabilitiesByCountryTable(), file)
    }
  )

  # cox_coefficients_by_country -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cox_coefficients_by_country <- TRUE
  }) |>
    shiny::bindEvent(
      input$cox_coefficients_by_country_cdm_name,
      input$cox_coefficients_by_country_cohort_name,
      input$cox_coefficients_by_country_variable_name,
      input$cox_coefficients_by_country_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cox_coefficients_by_country, {
    if (updateButtons$cox_coefficients_by_country == TRUE) {
      output$update_message_cox_coefficients_by_country <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cox_coefficients_by_country <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cox_coefficients_by_country, {
    updateButtons$cox_coefficients_by_country <- FALSE
  })

  ## get cox_coefficients_by_country data
  getCoxCoefficientsByCountryData <- shiny::eventReactive(input$update_cox_coefficients_by_country, {
    data[["cox_coefficients_by_country"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cox_coefficients_by_country_cdm_name,
        .data$variable_name %in% input$cox_coefficients_by_country_variable_name,
        .data$estimate_name %in% input$cox_coefficients_by_country_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$cox_coefficients_by_country_cohort_name) |>
      tidyr::pivot_wider(
        names_from = estimate_name,
        values_from = estimate_value
      ) |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se = as.numeric(se),
        coef_exp = round(exp(coef), digits = 2),
        lci = round(exp(coef - qnorm(0.975)*se), digits = 2),
        uci = round(exp(coef + qnorm(0.975)*se), digits = 2)
      ) |>
      dplyr::filter(uci != "Inf") |>
      dplyr::select(-c(coef, se, se_robust)) |>
      tidyr::pivot_longer(
        cols = c(coef_exp, lci, uci),
        names_to = "estimate_name",
        values_to = "estimate_value"
      ) |>
      dplyr::mutate(
        trans = stringr::str_extract(variable_level, "(?<=trans=)\\d+") |> as.numeric(),
        variable = stringr::str_extract(variable_level, "(?<=:)\\w+") |>
          stringr::str_remove("^sex")
      ) |>
      dplyr::mutate(trans = dplyr::case_when(
        trans == "1" ~ "Treatment -> No treatment",
        trans == "2" ~ "No treatment -> Treatment",
        trans == "3" ~ "Treatment -> Death",
        trans == "4" ~ "No treatment -> Death"
      )) |>
      dplyr::mutate(variable_level = paste0(trans, ": ", variable)) |>
      dplyr::select(-c(trans, variable)) |>
      dplyr::select(c(result_id, cdm_name, group_name, group_level, strata_name, strata_level, variable_name,
                      variable_level, estimate_name, estimate_type, estimate_value, additional_name, additional_level)) |>
      omopgenerics::newSummarisedResult()
  })
  getCoxCoefficientsByCountryTidy <- shiny::reactive({
    tidyDT(getCoxCoefficientsByCountryData(), input$cox_coefficients_by_country_tidy_columns, input$cox_coefficients_by_country_tidy_pivot_estimates)
  })
  output$cox_coefficients_by_country_tidy <- DT::renderDT({
    getCoxCoefficientsByCountryTidy()
  })
  output$cox_coefficients_by_country_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCoxCoefficientsByCountryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCoxCoefficientsByCountryTable <- shiny::reactive({
    getCoxCoefficientsByCountryData() |>
      simpleTable(
        header = input$cox_coefficients_by_country_table_header,
        group = input$cox_coefficients_by_country_table_group_column,
        hide = input$cox_coefficients_by_country_table_hide
      )
  })
  output$cox_coefficients_by_country_table <- gt::render_gt({
    getCoxCoefficientsByCountryTable()
  })
  output$cox_coefficients_by_country_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$cox_coefficients_by_country_table_format),
    content = function(file) {
      gt::gtsave(getCoxCoefficientsByCountryTable(), file)
    }
  )
}
