# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hds_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "estimate_name",
                      input_id = "summarise_omop_snapshot_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_omop_snapshot_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "variable_name",
                      input_id = "summarise_omop_snapshot_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "variable_level",
                      input_id = "summarise_omop_snapshot_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_omop_snapshot_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period Summary",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_observation_period",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_observation_period")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("observation_period_ordinal", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_observation_period_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_observation_period_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_observation_period_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "summarise_observation_period_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_observation_period_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CodelistGenerator",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_cohort_code_use",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_cohort_code_use")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name,
            selected = selected$cohort_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cohort_name",
            label = "Cohort name",
            choices = choices$cohort_code_use_cohort_name,
            selected = selected$cohort_code_use_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_codelist_name",
            label = "Codelist name",
            choices = choices$cohort_code_use_codelist_name,
            selected = selected$cohort_code_use_codelist_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_variable_name",
            label = "Variable name",
            choices = choices$cohort_code_use_variable_name,
            selected = selected$cohort_code_use_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_estimate_name",
            label = "Estimate name",
            choices = choices$cohort_code_use_estimate_name,
            selected = selected$cohort_code_use_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table Cohort code use (gt)",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_table_gt_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "cohort_code_use_table_gt_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "source_concept_value", "type_concept_id", "type_concept_name", "domain_id", "table", "variable_name", "variable_level"),
                      input_id = "cohort_code_use_table_gt_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "cohort_code_use_table_gt_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("cohort_code_use_table_gt") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CohortCharacteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_count",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_count")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_count_cdm_name,
            selected = selected$summarise_cohort_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_count_cohort_name,,
            selected = selected$summarise_cohort_count_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_count_variable_name,
            selected = selected$summarise_cohort_count_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "estimate_name"),
                      input_id = "summarise_cohort_count_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_count_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "table_name"),
                      input_id = "summarise_cohort_count_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_count_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_attrition_cohort_name,
            selected = selected$summarise_cohort_attrition_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "reason_id", "estimate_name", "age_range", "cdm_version", "cohort_definition_id", "gap", "min_future_observation", "min_prior_observation", "sex", "table_name", "vocabulary_version"),
                      input_id = "summarise_cohort_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_country",
            label = "Country",
            choices = choices$summarise_characteristics_country,
            selected = selected$summarise_characteristics_country,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_age_group",
            label = "Age group",
            choices = choices$summarise_characteristics_age_group,
            selected = selected$summarise_characteristics_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_sex",
            label = "Sex",
            choices = choices$summarise_characteristics_sex,
            selected = selected$summarise_characteristics_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_ses",
            label = "Ses",
            choices = choices$summarise_characteristics_ses,
            selected = selected$summarise_characteristics_ses,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("country", "age_group", "sex", "ses", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "country", "age_group", "sex", "ses"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "country", "age_group", "sex", "ses"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Logs",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_log_file",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_log_file")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_cdm_name",
          label = "CDM name",
          choices = choices$summarise_log_file_cdm_name,
          selected = selected$summarise_log_file_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_variable_name",
          label = "Variable name",
          choices = choices$summarise_log_file_variable_name,
          selected = selected$summarise_log_file_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Logs",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_log_file_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_log_file_table") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Timing",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_log_file_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_log_file_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_position",
                  label = "Columns",
                  choices = c("dodge", "stack"),
                  selected = "stack",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_log_file_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Crm probabilities",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_crm_probabilities",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_crm_probabilities")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_cdm_name",
          label = "CDM name",
          choices = choices$crm_probabilities_cdm_name,
          selected = selected$crm_probabilities_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_cohort_name",
          label = "Cohort name",
          choices = choices$crm_probabilities_cohort_name,
          selected = selected$crm_probabilities_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_time",
          label = "Time",
          choices = choices$crm_probabilities_time,
          selected = selected$crm_probabilities_time,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_state",
          label = "State",
          choices = choices$crm_probabilities_state,
          selected = selected$crm_probabilities_state,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_variable_name",
          label = "Variable name",
          choices = choices$crm_probabilities_variable_name,
          selected = selected$crm_probabilities_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_estimate_name",
          label = "Estimate name",
          choices = choices$crm_probabilities_estimate_name,
          selected = selected$crm_probabilities_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "crm_probabilities_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "crm_probabilities_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "crm_probabilities_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("crm_probabilities_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "crm_probabilities_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "crm_probabilities_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level", "estimate_name"),
                    input_id = "crm_probabilities_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "crm_probabilities_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "crm_probabilities_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "crm_probabilities_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("crm_probabilities_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Crm coefficients",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_crm_coefficients",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_crm_coefficients")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_cdm_name",
          label = "CDM name",
          choices = choices$crm_coefficients_cdm_name,
          selected = selected$crm_coefficients_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_cohort_name",
          label = "Cohort name",
          choices = choices$crm_coefficients_cohort_name,
          selected = selected$crm_coefficients_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_variable_name",
          label = "Variable name",
          choices = choices$crm_coefficients_variable_name,
          selected = selected$crm_coefficients_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_estimate_name",
          label = "Estimate name",
          choices = choices$crm_coefficients_estimate_name,
          selected = selected$crm_coefficients_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "crm_coefficients_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "crm_coefficients_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "crm_coefficients_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("crm_coefficients_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "crm_coefficients_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "crm_coefficients_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    input_id = "crm_coefficients_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "crm_coefficients_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "crm_coefficients_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "crm_coefficients_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("crm_coefficients_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Crm probabilities by country",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_crm_probabilities_by_country",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_crm_probabilities_by_country")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_cdm_name",
          label = "CDM name",
          choices = choices$crm_probabilities_by_country_cdm_name,
          selected = selected$crm_probabilities_by_country_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_cohort_name",
          label = "Cohort name",
          choices = choices$crm_probabilities_by_country_cohort_name,
          selected = selected$crm_probabilities_by_country_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_time",
          label = "Time",
          choices = choices$crm_probabilities_by_country_time,
          selected = selected$crm_probabilities_by_country_time,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_state",
          label = "State",
          choices = choices$crm_probabilities_by_country_state,
          selected = selected$crm_probabilities_by_country_state,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_variable_name",
          label = "Variable name",
          choices = choices$crm_probabilities_by_country_variable_name,
          selected = selected$crm_probabilities_by_country_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_probabilities_by_country_estimate_name",
          label = "Estimate name",
          choices = choices$crm_probabilities_by_country_estimate_name,
          selected = selected$crm_probabilities_by_country_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "crm_probabilities_by_country_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "crm_probabilities_by_country_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "crm_probabilities_by_country_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("crm_probabilities_by_country_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "crm_probabilities_by_country_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "crm_probabilities_by_country_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level", "estimate_name"),
                    input_id = "crm_probabilities_by_country_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "crm_probabilities_by_country_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "crm_probabilities_by_country_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "crm_probabilities_by_country_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("crm_probabilities_by_country_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Crm coefficients by country",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_crm_coefficients_by_country",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_crm_coefficients_by_country")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_by_country_cdm_name",
          label = "CDM name",
          choices = choices$crm_coefficients_by_country_cdm_name,
          selected = selected$crm_coefficients_by_country_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_by_country_cohort_name",
          label = "Cohort name",
          choices = choices$crm_coefficients_by_country_cohort_name,
          selected = selected$crm_coefficients_by_country_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_by_country_variable_name",
          label = "Variable name",
          choices = choices$crm_coefficients_by_country_variable_name,
          selected = selected$crm_coefficients_by_country_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "crm_coefficients_by_country_estimate_name",
          label = "Estimate name",
          choices = choices$crm_coefficients_by_country_estimate_name,
          selected = selected$crm_coefficients_by_country_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "crm_coefficients_by_country_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "crm_coefficients_by_country_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "crm_coefficients_by_country_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("crm_coefficients_by_country_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "crm_coefficients_by_country_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "crm_coefficients_by_country_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    input_id = "crm_coefficients_by_country_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "crm_coefficients_by_country_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "crm_coefficients_by_country_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "crm_coefficients_by_country_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("crm_coefficients_by_country_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Mms probabilities",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_mms_probabilities",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_mms_probabilities")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_cdm_name",
          label = "CDM name",
          choices = choices$mms_probabilities_cdm_name,
          selected = selected$mms_probabilities_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_cohort_name",
          label = "Cohort name",
          choices = choices$mms_probabilities_cohort_name,
          selected = selected$mms_probabilities_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_state",
          label = "State",
          choices = choices$mms_probabilities_state,
          selected = selected$mms_probabilities_state,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_variable_name",
          label = "Variable name",
          choices = choices$mms_probabilities_variable_name,
          selected = selected$mms_probabilities_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_estimate_name",
          label = "Estimate name",
          choices = choices$mms_probabilities_estimate_name,
          selected = selected$mms_probabilities_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "mms_probabilities_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "mms_probabilities_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "mms_probabilities_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("mms_probabilities_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "mms_probabilities_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "mms_probabilities_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level", "estimate_name"),
                    input_id = "mms_probabilities_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "mms_probabilities_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "mms_probabilities_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "mms_probabilities_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("mms_probabilities_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Cox coefficients",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_cox_coefficients",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_cox_coefficients")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_cdm_name",
          label = "CDM name",
          choices = choices$cox_coefficients_cdm_name,
          selected = selected$cox_coefficients_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_cohort_name",
          label = "Cohort name",
          choices = choices$cox_coefficients_cohort_name,
          selected = selected$cox_coefficients_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_variable_name",
          label = "Variable name",
          choices = choices$cox_coefficients_variable_name,
          selected = selected$cox_coefficients_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_estimate_name",
          label = "Estimate name",
          choices = choices$cox_coefficients_estimate_name,
          selected = selected$cox_coefficients_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "cox_coefficients_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "cox_coefficients_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "cox_coefficients_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("cox_coefficients_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "cox_coefficients_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "cox_coefficients_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    input_id = "cox_coefficients_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "cox_coefficients_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "cox_coefficients_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "cox_coefficients_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("cox_coefficients_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Mms probabilities by country",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_mms_probabilities_by_country",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_mms_probabilities_by_country")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_by_country_cdm_name",
          label = "CDM name",
          choices = choices$mms_probabilities_by_country_cdm_name,
          selected = selected$mms_probabilities_by_country_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_by_country_cohort_name",
          label = "Cohort name",
          choices = choices$mms_probabilities_by_country_cohort_name,
          selected = selected$mms_probabilities_by_country_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_by_country_state",
          label = "State",
          choices = choices$mms_probabilities_by_country_state,
          selected = selected$mms_probabilities_by_country_state,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_by_country_variable_name",
          label = "Variable name",
          choices = choices$mms_probabilities_by_country_variable_name,
          selected = selected$mms_probabilities_by_country_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "mms_probabilities_by_country_estimate_name",
          label = "Estimate name",
          choices = choices$mms_probabilities_by_country_estimate_name,
          selected = selected$mms_probabilities_by_country_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "mms_probabilities_by_country_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "mms_probabilities_by_country_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "mms_probabilities_by_country_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("mms_probabilities_by_country_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "mms_probabilities_by_country_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "mms_probabilities_by_country_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "time", "state", "variable_name", "variable_level", "estimate_name"),
                    input_id = "mms_probabilities_by_country_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "mms_probabilities_by_country_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "mms_probabilities_by_country_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "mms_probabilities_by_country_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("mms_probabilities_by_country_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Cox coefficients by country",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_cox_coefficients_by_country",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_cox_coefficients_by_country")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_by_country_cdm_name",
          label = "CDM name",
          choices = choices$cox_coefficients_by_country_cdm_name,
          selected = selected$cox_coefficients_by_country_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_by_country_cohort_name",
          label = "Cohort name",
          choices = choices$cox_coefficients_by_country_cohort_name,
          selected = selected$cox_coefficients_by_country_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_by_country_variable_name",
          label = "Variable name",
          choices = choices$cox_coefficients_by_country_variable_name,
          selected = selected$cox_coefficients_by_country_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "cox_coefficients_by_country_estimate_name",
          label = "Estimate name",
          choices = choices$cox_coefficients_by_country_estimate_name,
          selected = selected$cox_coefficients_by_country_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "cox_coefficients_by_country_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "cox_coefficients_by_country_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  selected = c("cdm_name", "cohort_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "cox_coefficients_by_country_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("cox_coefficients_by_country_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "cox_coefficients_by_country_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "cox_coefficients_by_country_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    input_id = "cox_coefficients_by_country_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "cox_coefficients_by_country_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "cox_coefficients_by_country_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "cox_coefficients_by_country_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("cox_coefficients_by_country_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
