# Generated by OmopViewer 0.6.0.900
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    cohort_code_use = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_cohort_name,
      input$cohort_code_use_codelist_name,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name %in% input$cohort_code_use_cohort_name,
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_count <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_count_cdm_name,
      input$summarise_cohort_count_cohort_name,
      input$summarise_cohort_count_variable_name,
      input$summarise_cohort_count_table_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })

  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_age_group,
      input$summarise_characteristics_sex,
      input$summarise_characteristics_ses,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$sex %in% input$summarise_characteristics_sex,
        .data$ses %in% input$summarise_characteristics_ses
      )
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
}
