# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )

  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::reactive({
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name
      )
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    res <- getSummariseObservationPeriodData()
    res |>
      OmopSketch::tableObservationPeriod(
        hide = c(omopgenerics::settingsColumns(res), "observation_period_ordinal"),
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::reactive({
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        hide = "timing"
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_count -----
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::reactive({
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name)
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      dplyr::filter(variable_name == "Number subjects") |>
      CohortCharacteristics::tableCohortCount(
        header = "cdm_name",
        groupColumn = c("cohort_name"),
        hide = c("variable_level", "table_name", "estimate_name")
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::reactive({
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition()
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_demographics -----
  ## get summarise_demographics data
  getSummariseDemographicsData <- shiny::reactive({
    data[["summarise_demographics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_demographics_cdm_name,
        .data$variable_name %in% input$summarise_demographics_variable_name,
        .data$estimate_name %in% input$summarise_demographics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_demographics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$strata %in% input$summarise_demographics_strata
      )
  })
  getSummariseDemographicsTable <- shiny::reactive({
    getSummariseDemographicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_demographics_table_header,
        groupColumn = input$summarise_demographics_table_group_column,
        hide = input$summarise_demographics_table_hide
      )
  })
  output$summarise_demographics_table <- gt::render_gt({
    getSummariseDemographicsTable()
  })
  output$summarise_demographics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_demographics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDemographicsTable(), file)
    }
  )
  getSummariseDemographicsPlot <- shiny::reactive({
    getSummariseDemographicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_demographics_plot_plot_type,
        facet = input$summarise_demographics_plot_facet,
        colour = input$summarise_demographics_plot_colour
      )
  })
  output$summarise_demographics_plot <- shiny::renderUI({
    x <- getSummariseDemographicsPlot()
    renderInteractivePlot(x, input$summarise_demographics_plot_interactive)
  })
  output$summarise_demographics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseDemographicsPlot(),
        width = as.numeric(input$summarise_demographics_plot_width),
        height = as.numeric(input$summarise_demographics_plot_height),
        units = input$summarise_demographics_plot_units,
        dpi = as.numeric(input$summarise_demographics_plot_dpi)
      )
    }
  )

  # summarise_treatments -----
  ## get summarise_treatments data
  getSummariseTreatmentsData <- shiny::reactive({
    x <- data[["summarise_treatments"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_treatments_cdm_name,
        .data$variable_name %in% input$summarise_treatments_variable_name,
        .data$variable_level %in% input$summarise_treatments_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_treatments_cohort_name)
    inx <- input$summarise_treatments_strata
    if (!"overall" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(strata != "overall")
    }
    if (!"age_group" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("Age", strata))
    }
    if (!"sex" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("SES", strata))
    }
    if (!"ses" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("Sex", strata))
    }
    x
  })
  getSummariseTreatmentsTable <- shiny::reactive({
    getSummariseTreatmentsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_treatments_table_header,
        groupColumn = input$summarise_treatments_table_group_column,
        hide = input$summarise_treatments_table_hide
      )
  })
  output$summarise_treatments_table <- gt::render_gt({
    getSummariseTreatmentsTable()
  })
  output$summarise_treatments_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_treatments_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTreatmentsTable(), file)
    }
  )
  getSummariseTreatmentsPlot <- shiny::reactive({
    x <- getSummariseTreatmentsData() |>
      omopgenerics::tidy()
    visOmopResults::barPlot(
      result = x,
      x = "variable_level",
      y = "percentage",
      facet = input$summarise_treatments_plot_facet,
      colour = input$summarise_treatments_plot_colour
    ) +
      ggplot2::coord_flip()
  })
  output$summarise_treatments_plot <- shiny::renderUI({
    x <- getSummariseTreatmentsPlot()
    renderInteractivePlot(x, input$summarise_treatments_plot_interactive)
  })
  output$summarise_treatments_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseTreatmentsPlot(),
        width = as.numeric(input$summarise_treatments_plot_width),
        height = as.numeric(input$summarise_treatments_plot_height),
        units = input$summarise_treatments_plot_units,
        dpi = as.numeric(input$summarise_treatments_plot_dpi)
      )
    }
  )

  # summarise_procedures -----
  ## get summarise_procedures data
  getSummariseProceduresData <- shiny::reactive({
    x <- data[["summarise_procedures"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_procedures_cdm_name,
        .data$variable_name %in% input$summarise_procedures_variable_name,
        .data$estimate_name %in% input$summarise_procedures_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_procedures_cohort_name)
    inx <- input$summarise_treatments_strata
    if (!"overall" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(strata != "overall")
    }
    if (!"age_group" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("Age", strata))
    }
    if (!"sex" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("SES", strata))
    }
    if (!"ses" %in% inx) {
      x <- x |>
        omopgenerics::filterStrata(!grepl("Sex", strata))
    }
    x
  })
  getSummariseProceduresTable <- shiny::reactive({
    getSummariseProceduresData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_procedures_table_header,
        groupColumn = input$summarise_procedures_table_group_column,
        hide = input$summarise_procedures_table_hide
      )
  })
  output$summarise_procedures_table <- gt::render_gt({
    getSummariseProceduresTable()
  })
  output$summarise_procedures_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_procedures_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresTable(), file)
    }
  )
  getSummariseProceduresPlot <- shiny::reactive({
    x <- getSummariseProceduresData() |>
      omopgenerics::tidy()
    visOmopResults::barPlot(
      result = x,
      x = "variable_level",
      y = "percentage",
      facet = input$summarise_treatments_plot_facet,
      colour = input$summarise_treatments_plot_colour
    ) +
      ggplot2::coord_flip()
  })
  output$summarise_procedures_plot <- shiny::renderUI({
    x <- getSummariseProceduresPlot()
    renderInteractivePlot(x, input$summarise_procedures_plot_interactive)
  })
  output$summarise_procedures_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseProceduresPlot(),
        width = as.numeric(input$summarise_procedures_plot_width),
        height = as.numeric(input$summarise_procedures_plot_height),
        units = input$summarise_procedures_plot_units,
        dpi = as.numeric(input$summarise_procedures_plot_dpi)
      )
    }
  )
}
