# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  # intro duction ----
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),

  ## diagnostics ----
  bslib::nav_menu(
    title = "Diagnostics",
    icon = shiny::icon("list"),

    ### snapshot ----
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::card(
          full_screen = TRUE,
          bslib::card_header(
            bslib::popover(
              shiny::icon("download"),
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_table_format",
                label = "Format",
                choices = c("docx", "png", "pdf", "html"),
                selected = "docx",
                multiple = FALSE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
            ),
            class = "text-end"
          ),
          gt::gt_output("summarise_omop_snapshot_table") |>
            shinycssloaders::withSpinner()
        )
      )
    ),

    ### observation period ----
    bslib::nav_panel(
      title = "Observation period Summary",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name"),
                    selected = nullfile(),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),

    ### cohort code use ----
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name,
            selected = selected$cohort_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_codelist_name",
            label = "Codelist name",
            choices = choices$cohort_code_use_codelist_name,
            selected = selected$cohort_code_use_codelist_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_estimate_name",
            label = "Estimate name",
            choices = choices$cohort_code_use_estimate_name,
            selected = selected$cohort_code_use_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table Cohort code use (gt)",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_table_gt_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "cohort_code_use_table_gt_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "source_concept_value", "type_concept_id", "type_concept_name", "domain_id", "table", "variable_name", "variable_level"),
                      input_id = "cohort_code_use_table_gt_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "cohort_code_use_table_gt_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("cohort_code_use_table_gt") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),

  ## characterisation ----
  bslib::nav_menu(
    title = "Characteristics",
    icon = shiny::icon("list"),

    ### counts ----
    bslib::nav_panel(
      title = "Cohort Count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_count_cdm_name,
            selected = selected$summarise_cohort_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_count_cohort_name,
            selected = selected$summarise_cohort_count_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_cohort_count_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_count_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),

    ### attrition ----
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_attrition_cohort_name,
            selected = selected$summarise_cohort_attrition_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_cohort_attrition_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),

    ### demographics ----
    bslib::nav_panel(
      title = "Summarise demographics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_demographics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_demographics_cdm_name,
            selected = selected$summarise_demographics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_demographics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_demographics_cohort_name,
            selected = selected$summarise_demographics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_demographics_strata",
            label = "Strata",
            choices = choices$summarise_demographics_strata,
            selected = selected$summarise_demographics_strata,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_demographics_variable_name",
            label = "Variable name",
            choices = choices$summarise_demographics_variable_name,
            selected = selected$summarise_demographics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_demographics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_demographics_estimate_name,
            selected = selected$summarise_demographics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_demographics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_demographics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("strata", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_demographics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_demographics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_demographics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_demographics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_demographics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_demographics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_demographics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_demographics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_demographics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_demographics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_demographics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_demographics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_demographics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex", "ses"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_demographics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex", "ses"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_demographics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),

    ### treatments ----
    bslib::nav_panel(
      title = "Summarise treatments",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_treatments_cdm_name",
            label = "CDM name",
            choices = choices$summarise_treatments_cdm_name,
            selected = selected$summarise_treatments_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_treatments_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_treatments_cohort_name,
            selected = selected$summarise_treatments_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_treatments_strata",
            label = "Strata",
            choices = c("overall", "age_group", "ses", "sex"),
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_treatments_variable_name",
            label = "Variable name",
            choices = choices$summarise_treatments_variable_name,
            selected = selected$summarise_treatments_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_treatments_variable_level",
            label = "Treatments",
            choices = choices$summarise_treatments_variable_level,
            selected = selected$summarise_treatments_variable_level,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_treatments_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_treatments_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("strata", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_treatments_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_treatments_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_treatments_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_treatments_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_treatments_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Treatments",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_treatments_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_treatments_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_treatments_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_treatments_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_treatments_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_treatments_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_treatments_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "strata"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_treatments_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "strata"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_treatments_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),

    ### procedures ----
    bslib::nav_panel(
      title = "Summarise procedures",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_cdm_name",
            label = "CDM name",
            choices = choices$summarise_procedures_cdm_name,
            selected = selected$summarise_procedures_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_procedures_cohort_name,
            selected = selected$summarise_procedures_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_strata",
            label = "Strata",
            choices = c("overall", "age_group", "ses", "sex"),
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_variable_name",
            label = "Variable name",
            choices = choices$summarise_procedures_variable_name,
            selected = selected$summarise_procedures_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_procedures_estimate_name,
            selected = selected$summarise_procedures_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_procedures_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("age_group", "sex", "ses", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_procedures_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_procedures_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_procedures_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_procedures_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_procedures_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_procedures_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_procedures_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_procedures_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_procedures_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_procedures_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex", "ses"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "age_group", "sex", "ses"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_procedures_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),

  ## download ----
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
  ## end ----
)
